public class Art
{
    public static void CosmOS()
    {
        Console.ForegroundColor = ConsoleColor.DarkRed;
        Console.Write(@"   ______  ");
        Console.ForegroundColor = ConsoleColor.Cyan;
        Console.Write(@"                                          ______    ");
        Console.ForegroundColor = ConsoleColor.Blue;
        Console.WriteLine(@"______");
        Console.ForegroundColor = ConsoleColor.DarkRed;
        Console.Write(@"  /      \");
        Console.ForegroundColor = ConsoleColor.Cyan;
        Console.Write(@"                                          /      \");
        Console.ForegroundColor = ConsoleColor.Blue;
        Console.WriteLine(@"  /      \");
        Console.ForegroundColor = ConsoleColor.DarkRed;
        Console.Write(@" /$$$$$$  |");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write(@"  ______");
        Console.ForegroundColor = ConsoleColor.Yellow;
        Console.Write(@"    _______");
        Console.ForegroundColor = ConsoleColor.Green;
        Console.Write(@"  _____  ____");
        Console.ForegroundColor = ConsoleColor.Cyan;
        Console.Write(@"        /$$$$$$  |");
        Console.ForegroundColor = ConsoleColor.Blue;
        Console.WriteLine(@"/$$$$$$  |");
        Console.ForegroundColor = ConsoleColor.DarkRed;
        Console.Write(@" $$ |  $$/");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write(@"  /      \");
        Console.ForegroundColor = ConsoleColor.Yellow;
        Console.Write(@"  /       |");
        Console.ForegroundColor = ConsoleColor.Green;
        Console.Write(@"/     \/    \");
        Console.ForegroundColor = ConsoleColor.Cyan;
        Console.Write(@"       $$ |  $$ |");
        Console.ForegroundColor = ConsoleColor.Blue;
        Console.WriteLine(@"$$ \__$$/");
        Console.ForegroundColor = ConsoleColor.DarkRed;
        Console.Write(@" $$ |");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write(@"      /$$$$$$  |");
        Console.ForegroundColor = ConsoleColor.Yellow;
        Console.Write(@"/$$$$$$$/");
        Console.ForegroundColor = ConsoleColor.Green;
        Console.Write(@" $$$$$$ $$$$  |");
        Console.ForegroundColor = ConsoleColor.Cyan;
        Console.Write(@"      $$ |  $$ |");
        Console.ForegroundColor = ConsoleColor.Blue;
        Console.WriteLine(@"$$      \");
        Console.ForegroundColor = ConsoleColor.DarkRed;
        Console.Write(@" $$ |   __");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write(@" $$ |  $$ |");
        Console.ForegroundColor = ConsoleColor.Yellow;
        Console.Write(@"$$      \");
        Console.ForegroundColor = ConsoleColor.Green;
        Console.Write(@" $$ | $$ | $$ |");
        Console.ForegroundColor = ConsoleColor.Cyan;
        Console.Write(@"      $$ |  $$ | ");
        Console.ForegroundColor = ConsoleColor.Blue;
        Console.WriteLine(@"$$$$$$  |");
        Console.ForegroundColor = ConsoleColor.DarkRed;
        Console.Write(@" $$ \__/  |");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write(@"$$ \__$$ |");
        Console.ForegroundColor = ConsoleColor.Yellow;
        Console.Write(@" $$$$$$  |");
        Console.ForegroundColor = ConsoleColor.Green;
        Console.Write(@"$$ | $$ | $$ |");
        Console.ForegroundColor = ConsoleColor.Cyan;
        Console.Write(@"      $$ \__$$ |");
        Console.ForegroundColor = ConsoleColor.Blue;
        Console.WriteLine(@"/  \__$$ |");
        Console.ForegroundColor = ConsoleColor.DarkRed;
        Console.Write(@" $$    $$/");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write(@" $$    $$/");
        Console.ForegroundColor = ConsoleColor.Yellow;
        Console.Write(@" /     $$/");
        Console.ForegroundColor = ConsoleColor.Green;
        Console.Write(@" $$ | $$ | $$ |");
        Console.ForegroundColor = ConsoleColor.Cyan;
        Console.Write(@"      $$    $$/");
        Console.ForegroundColor = ConsoleColor.Blue;
        Console.WriteLine(@" $$    $$/");
        Console.ForegroundColor = ConsoleColor.DarkRed;
        Console.Write(@"  $$$$$$/");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write(@"   $$$$$$/");
        Console.ForegroundColor = ConsoleColor.Yellow;
        Console.Write(@"  $$$$$$$/");
        Console.ForegroundColor = ConsoleColor.Green;
        Console.Write(@"  $$/  $$/  $$/");
        Console.ForegroundColor = ConsoleColor.Cyan;
        Console.Write(@"        $$$$$$/");
        Console.ForegroundColor = ConsoleColor.Blue;
        Console.WriteLine(@"   $$$$$$/");
    }

}